-- Create Employee table
CREATE TABLE IF NOT EXISTS public.employee
(
    employeeid bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT employee_pkey PRIMARY KEY (employeeid),
    CONSTRAINT employee_email_key UNIQUE (email)
)


-- Create SelfReview table
CREATE TABLE SelfReview (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    review_text TEXT NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    FOREIGN KEY (employeeid) REFERENCES Employee(employeeid)
);

-- Create ManagerReview table
CREATE TABLE ManagerReview (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    review_text TEXT NOT NULL,
    rating DECIMAL(2,1) NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    FOREIGN KEY (employeeid) REFERENCES Employee(employeeid)
);
